name: run

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-12
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: git clone towards5gs-helm
        run: git clone https://github.com/Orange-OpenSource/towards5gs-helm.git

      - name: Run vagrant up
        run: vagrant up
